name: start

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: test
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Do it!
        uses: ./.github/actions/semantic-release-action

      # - run: node --version

      # - run: echo ${{ secrets.GITHUB_TOKEN }}

      # - run: curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release && chmod +x ./semantic-release

      # - run: ls -a

      # - run: git --no-pager log 

      # - run: ./semantic-release -f --no-ci

      # - run: ls -a
